version: 2

python:
  version: "3.8"
  install:
    - requirements: requirements.txt

build:
  image: latest

# Build documentation in the source/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Setup submodules
submodules:
  include: all
